documentation:
  - changed-files:
      - any-glob-to-any-file: 'docs/**'

ml-model:
  - changed-files:
      - any-glob-to-any-file: 'notebooks/**'

ci-cd:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

frontend:
  - changed-files:
      - any-glob-to-any-file: 'frontend/**'

backend:
  - changed-files:
      - any-glob-to-any-file: 'backend/**'

python:
  - changed-files:
      - any-glob-to-any-file: '*.py'

jupyter-notebook:
  - changed-files:
      - any-glob-to-any-file: '*.ipynb'
